### ISSUE TITLE
logging 

### ISSUE THREAD

**Issue by Christianivh** [JohnnyLVP/Project-Standar-Documentation#3]
agregar como manejar un logging:

**oficial logging**
https://docs.python-guide.org/writing/logging/

**simple**
https://realpython.com/python-logging/

**restapi logging**
https://pypi.org/project/restapi-logging-handler/

**instumentacion library**
https://blog.appoptics.com/building-a-code-instrumentation-library-with-python-and-zeromq/

**pagando**
https://www.loggly.com/docs/python-http/

**Comment by JohnnyLVP** [comment]
se agrego la Clase en Python para utilizar el ApiLog **./model-pipeline/apilog/**
